name: 💡 Feature Request
description: Request a feature/enhancement
labels: ["type: :bulb: enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: |
        Please search to see if an feature request like this already exists.

        Tip: You can go to the [GitHub issue tab](https://github.com/SkinsRestorer/SkinsRestorer/labels/type%3A%20%3Abulb%3A%20enhancement) for a list of open feature requests
      options:
      - label: I have searched the existing feature requests
        required: true
  - type: textarea
    attributes:
      label: Describe your feature request
      description: What do you want added to SkinsRestorer?
      placeholder: "I want x feature added to SkinsRestorer"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Explain what you need this for
      description: What do you want to use this feature for?
      placeholder: "I want to use this to do x on my server"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Links to other relevant places. Like internet articles or links to Discord messages.
      placeholder: "e.g. https://discord.com/channels/xxx/xxx/xxx"
