name: Attach release hashes

on: [ release ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: robinraju/release-downloader@v1.10
      with:
        latest: true
        fileName: 'SkinsRestorer.jar'
    - run: |
        sha256sum SkinsRestorer.jar > sha256.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sha256.txt
