name: Attach release hash

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: robinraju/release-downloader@v1.10
      with:
        latest: true
        fileName: 'SkinsRestorer.jar'
    - run: |
        sha256sum SkinsRestorer.jar > verification-hash.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: verification-hash.txt
